import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, NavLink, Outlet } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
const linkClass = ({ isActive }) => `rounded-md px-3 py-2 text-sm font-medium ${isActive ? "bg-white text-tmobile shadow-sm" : "text-gray-700 hover:bg-white/60"}`;
export default function AppShell() {
    const { user, logout } = useAuth();
    const role = user?.role;
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("header", { className: "border-b border-gray-200 bg-white", children: _jsxs("div", { className: "mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-3", children: [_jsx(Link, { to: "/app", className: "text-xl font-bold text-tmobile", children: "TicketIQ" }), _jsxs("nav", { className: "flex flex-wrap items-center gap-1", children: [_jsx(NavLink, { to: "/app/tickets", className: linkClass, children: role === "end_user" ? "My tickets" : "All tickets" }), _jsx(NavLink, { to: "/app/submit", className: linkClass, children: "Submit" }), (role === "it_support" || role === "admin") && (_jsx(NavLink, { to: "/app/queue", className: linkClass, children: "Queue" })), (role === "it_support" || role === "admin") && (_jsx(NavLink, { to: "/app/best-fit", className: linkClass, children: "Best fit" })), role === "admin" && (_jsxs(_Fragment, { children: [_jsx(NavLink, { to: "/app/admin/audit", className: linkClass, children: "Audit log" }), _jsx(NavLink, { to: "/app/admin/escalation", className: linkClass, children: "Escalation" })] }))] }), _jsxs("div", { className: "flex items-center gap-3 text-sm text-gray-600", children: [_jsxs("span", { children: [user?.full_name, _jsx("span", { className: "ml-2 rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-700", children: user?.role })] }), _jsx("button", { type: "button", onClick: logout, className: "rounded-md border border-gray-300 px-3 py-1.5 text-gray-800 hover:bg-gray-100", children: "Log out" })] })] }) }), _jsx("main", { className: "mx-auto max-w-6xl px-4 py-6", children: _jsx(Outlet, {}) })] }));
}
