"""

Revision ID: 52b62599dc01
Revises: ae85b8a65358
Create Date: 2026-05-04 04:16:08.488647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b62599dc01'
down_revision = 'ae85b8a65358'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
