"""

Revision ID: 54bf25b5be1e
Revises: fe456b2754d5
Create Date: 2026-05-04 05:31:30.615553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bf25b5be1e'
down_revision = 'fe456b2754d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
