// import type {
//   AuditLog,
//   EscalationRule,
//   EscalationRuleVersion,
//   IssueCategory,
//   Note,
//   Ticket,
//   User,
//   WeeklyReport,
// } from "./types";
//
// export const MOCK_USERS: User[] = [
//   {
//     userId: "u-admin-1",
//     name: "Priya Sharma",
//     email: "priya.sharma@t-mobile.com",
//     role: "admin",
//     department: "IT Operations",
//     region: "Bellevue HQ",
//   },
//   {
//     userId: "u-admin-2",
//     name: "Marcus Chen",
//     email: "marcus.chen@t-mobile.com",
//     role: "admin",
//     department: "Enterprise Security",
//     region: "Frisco",
//   },
//   {
//     userId: "u-tech-1",
//     name: "Jordan Lee",
//     email: "jordan.lee@t-mobile.com",
//     role: "technician",
//     department: "NOC",
//     region: "Nevada",
//     specializations: ["network", "security"],
//   },
//   {
//     userId: "u-tech-2",
//     name: "Sam Rivera",
//     email: "sam.rivera@t-mobile.com",
//     role: "technician",
//     department: "Desktop Support",
//     region: "Texas",
//     specializations: ["software", "hardware", "account"],
//   },
//   {
//     userId: "u-tech-3",
//     name: "Alex Nguyen",
//     email: "alex.nguyen@t-mobile.com",
//     role: "technician",
//     department: "Identity & Access",
//     region: "Washington",
//     specializations: ["account", "security"],
//   },
//   {
//     userId: "u-user-1",
//     name: "Taylor Brooks",
//     email: "taylor.brooks@t-mobile.com",
//     role: "user",
//     department: "Retail Operations",
//     region: "California",
//   },
//   {
//     userId: "u-user-2",
//     name: "Riley Patel",
//     email: "riley.patel@t-mobile.com",
//     role: "user",
//     department: "Care",
//     region: "New York",
//   },
//   {
//     userId: "u-user-3",
//     name: "Casey Morgan",
//     email: "casey.morgan@t-mobile.com",
//     role: "user",
//     department: "Engineering",
//     region: "Washington",
//   },
// ];
//
// const n = (
//   noteId: string,
//   authorId: string,
//   content: string,
//   createdAt: string,
//   visibleToUser: boolean,
// ): Note => ({
//   noteId,
//   authorId,
//   content,
//   createdAt,
//   visibleToUser,
// });
//
// export const MOCK_TICKETS_SEED: Ticket[] = [
//   {
//     ticketId: "TM-240891",
//     title: "Corporate VPN disconnects every 15 minutes",
//     submittedBy: "u-user-1",
//     description:
//       "Pulse Secure VPN drops intermittently on macOS 14. Reconnect works but sessions terminate during Teams calls. Affects Bellevue retail pilot Wi‑Fi backhaul tests.",
//     affectedSystem: "Pulse Secure / GlobalProtect bridge",
//     category: "network",
//     severity: "high",
//     urgency: "high",
//     priorityScore: 88,
//     status: "in_progress",
//     assignedTo: "u-tech-1",
//     createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
//     attachments: ["vpn-logs-redacted.zip"],
//     internalNotes: [
//       n(
//         "note-1",
//         "u-tech-1",
//         "Seeing MTU black-hole on split tunnel. Testing MSS clamp on gateway cluster NV-03.",
//         new Date(Date.now() - 1000 * 60 * 30).toISOString(),
//         false,
//       ),
//     ],
//     aiConfidence: 0.91,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 55).toISOString(),
//     region: "California",
//   },
//   {
//     ticketId: "TM-240892",
//     title: "Outlook fails to sync shared mailboxes after tenant move",
//     submittedBy: "u-user-2",
//     description:
//       "Exchange Online shared mailboxes show 'Need Password' loop after EXO migration wave 4B. Cached mode repair did not resolve.",
//     affectedSystem: "Microsoft Outlook 365",
//     category: "software",
//     severity: "medium",
//     urgency: "medium",
//     priorityScore: 62,
//     status: "assigned",
//     assignedTo: "u-tech-2",
//     createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
//     aiConfidence: 0.84,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 240).toISOString(),
//     region: "New York",
//   },
//   {
//     ticketId: "TM-240893",
//     title: "Retail POS handheld offline — store 4421",
//     submittedBy: "u-user-1",
//     description:
//       "All handheld scanners lost LTE failover during regional carrier maintenance. Store unable to process exchanges for ~40 minutes.",
//     affectedSystem: "Retail POS / Cradlepoint edge",
//     category: "hardware",
//     severity: "critical",
//     urgency: "high",
//     priorityScore: 96,
//     status: "escalated",
//     assignedTo: "u-tech-2",
//     createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
//     escalatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
//     internalNotes: [
//       n(
//         "note-2",
//         "u-tech-2",
//         "Escalated to carrier TAM — incident INC-99221 linked.",
//         new Date(Date.now() - 1000 * 60 * 22).toISOString(),
//         false,
//       ),
//     ],
//     aiConfidence: 0.94,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 25).toISOString(),
//     region: "Texas",
//   },
//   {
//     ticketId: "TM-240894",
//     title: "SSL certificate expiring on partner API gateway",
//     submittedBy: "u-user-3",
//     description:
//       "DigiCert cert on api.partner.t-mobile.com expires in 6 days. Renewal workflow stuck in Akamai pending approval.",
//     affectedSystem: "Akamai / API gateway",
//     category: "security",
//     severity: "high",
//     urgency: "medium",
//     priorityScore: 79,
//     status: "open",
//     createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
//     aiConfidence: 0.88,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 180).toISOString(),
//     region: "Washington",
//   },
//   {
//     ticketId: "TM-240895",
//     title: "Wi‑Fi outage — campus building C floor 3",
//     submittedBy: "u-user-3",
//     description:
//       "Meraki APs reporting DHCP exhaustion on VLAN 118. Users falling back to guest SSID with limited internal reach.",
//     affectedSystem: "Meraki MR / Catalyst core",
//     category: "network",
//     severity: "high",
//     urgency: "high",
//     priorityScore: 85,
//     status: "escalated",
//     assignedTo: "u-tech-1",
//     createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
//     escalatedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
//     aiConfidence: 0.9,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 40).toISOString(),
//     region: "Washington",
//   },
//   {
//     ticketId: "TM-240896",
//     title: "Laptop thermal shutdown during diagnostics",
//     submittedBy: "u-user-2",
//     description:
//       "Engineering loaner ThinkPad P1 Gen 6 powers off under GPU load. Fan curves look normal in Lenovo Vantage.",
//     affectedSystem: "Lenovo ThinkPad P1",
//     category: "hardware",
//     severity: "medium",
//     urgency: "low",
//     priorityScore: 48,
//     status: "in_progress",
//     assignedTo: "u-tech-2",
//     createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
//     aiConfidence: 0.76,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 400).toISOString(),
//     region: "New York",
//   },
//   {
//     ticketId: "TM-240897",
//     title: "Okta push MFA delays for Care queues",
//     submittedBy: "u-user-2",
//     description:
//       "Agents report 20–40s delay on Okta Verify push during peak. SSO to Salesforce unaffected.",
//     affectedSystem: "Okta Workforce Identity",
//     category: "account",
//     severity: "medium",
//     urgency: "high",
//     priorityScore: 71,
//     status: "assigned",
//     assignedTo: "u-tech-3",
//     createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
//     aiConfidence: 0.82,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 150).toISOString(),
//     region: "New York",
//   },
//   {
//     ticketId: "TM-240898",
//     title: "SIEM alert storm — duplicate DNS tunneling rules",
//     submittedBy: "u-admin-1",
//     description:
//       "Splunk ES notable count spiked after rule pack import. False positives from internal resolver traffic.",
//     affectedSystem: "Splunk ES / Enterprise Security",
//     category: "security",
//     severity: "low",
//     urgency: "medium",
//     priorityScore: 42,
//     status: "resolved",
//     assignedTo: "u-tech-1",
//     createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
//     resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
//     internalNotes: [
//       n(
//         "note-3",
//         "u-tech-1",
//         "Tuned correlation search CS-DNS-014; verified with SecOps sign-off.",
//         new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
//         false,
//       ),
//     ],
//     aiConfidence: 0.79,
//     slaDeadline: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
//     region: "Bellevue HQ",
//   },
//   {
//     ticketId: "TM-240899",
//     title: "SAP GUI script blocked by new AppLocker policy",
//     submittedBy: "u-user-3",
//     description:
//       "Finance batch job launcher blocked after GPO refresh. Hash rule missing for saplogon.exe secondary path.",
//     affectedSystem: "Windows AppLocker / SAP GUI 800",
//     category: "software",
//     severity: "medium",
//     urgency: "medium",
//     priorityScore: 58,
//     status: "open",
//     createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
//     aiConfidence: 0.86,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 200).toISOString(),
//     region: "Washington",
//   },
//   {
//     ticketId: "TM-240900",
//     title: "Badge reader offline — Frisco DC dock 7",
//     submittedBy: "u-user-1",
//     description:
//       "Lenel reader fault after firmware push. Contractors unable to badge in without guard override.",
//     affectedSystem: "Lenel OnGuard reader cluster",
//     category: "hardware",
//     severity: "high",
//     urgency: "high",
//     priorityScore: 81,
//     status: "in_progress",
//     assignedTo: "u-tech-2",
//     createdAt: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
//     aiConfidence: 0.87,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 90).toISOString(),
//     region: "Texas",
//   },
//   {
//     ticketId: "TM-240901",
//     title: "Email delay to partner domain — greylisting suspected",
//     submittedBy: "u-user-2",
//     description:
//       "Outbound to vendor shows 45min latency. Message trace shows queuing on edge EOP in region WEU.",
//     affectedSystem: "Exchange Online Protection",
//     category: "network",
//     severity: "low",
//     urgency: "medium",
//     priorityScore: 39,
//     status: "resolved",
//     assignedTo: "u-tech-3",
//     createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
//     resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
//     aiConfidence: 0.73,
//     slaDeadline: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
//     region: "New York",
//   },
//   {
//     ticketId: "TM-240902",
//     title: "Privileged session recording failures",
//     submittedBy: "u-admin-2",
//     description:
//       "CyberArk PTA intermittently drops Windows session recordings for jump hosts in subnet 10.42.x.",
//     affectedSystem: "CyberArk PTA",
//     category: "security",
//     severity: "critical",
//     urgency: "high",
//     priorityScore: 93,
//     status: "escalated",
//     assignedTo: "u-tech-3",
//     createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
//     escalatedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
//     aiConfidence: 0.92,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 35).toISOString(),
//     region: "Frisco",
//   },
//   {
//     ticketId: "TM-240903",
//     title: "Printer fleet driver mismatch after Win11 23H2",
//     submittedBy: "u-user-1",
//     description:
//       "Universal Print jobs stall at 'Rendering' for Ricoh IM C4500. Issue isolated to 23H2 pilot ring.",
//     affectedSystem: "Universal Print / Ricoh IM series",
//     category: "software",
//     severity: "low",
//     urgency: "low",
//     priorityScore: 31,
//     status: "archived",
//     assignedTo: "u-tech-2",
//     createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
//     resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
//     aiConfidence: 0.68,
//     slaDeadline: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
//     region: "California",
//   },
//   {
//     ticketId: "TM-240904",
//     title: "Core switch CRC errors — POP east aggregation",
//     submittedBy: "u-tech-1",
//     description:
//       "Nexus 9k interfaces toward DWDM showing rising CRCs. Optics swapped; issue persists on port E1/49.",
//     affectedSystem: "Cisco Nexus 93180",
//     category: "network",
//     severity: "critical",
//     urgency: "high",
//     priorityScore: 97,
//     status: "open",
//     createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
//     aiConfidence: 0.95,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 45).toISOString(),
//     region: "Nevada",
//   },
//   {
//     ticketId: "TM-240905",
//     title: "Self-service password reset SMS not delivered",
//     submittedBy: "u-user-3",
//     description:
//       "T-Mobile ID SMS OTP not arriving for @gsm.t-mobile.com test accounts in staging tenant.",
//     affectedSystem: "T-Mobile ID / SMS gateway",
//     category: "account",
//     severity: "medium",
//     urgency: "medium",
//     priorityScore: 55,
//     status: "assigned",
//     assignedTo: "u-tech-3",
//     createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
//     updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
//     aiConfidence: 0.8,
//     slaDeadline: new Date(Date.now() + 1000 * 60 * 220).toISOString(),
//     region: "Washington",
//   },
// ];
//
// export const MOCK_AUDIT_LOGS: AuditLog[] = [
//   {
//     logId: "al-001",
//     actorId: "u-admin-1",
//     actorType: "admin",
//     actionType: "override",
//     ticketId: "TM-240893",
//     oldValue: "severity:high",
//     newValue: "severity:critical",
//     reason: "Retail revenue impact confirmed by store director.",
//     timestamp: new Date(Date.now() - 1000 * 60 * 26).toISOString(),
//   },
//   {
//     logId: "al-002",
//     actorId: "system",
//     actorType: "system",
//     actionType: "classification",
//     ticketId: "TM-240891",
//     oldValue: "",
//     newValue: "network/high",
//     timestamp: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
//   },
//   {
//     logId: "al-003",
//     actorId: "u-tech-1",
//     actorType: "technician",
//     actionType: "reassignment",
//     ticketId: "TM-240895",
//     oldValue: "u-tech-2",
//     newValue: "u-tech-1",
//     reason: "NOC ownership for Meraki stack.",
//     timestamp: new Date(Date.now() - 1000 * 60 * 16).toISOString(),
//   },
//   {
//     logId: "al-004",
//     actorId: "system",
//     actorType: "system",
//     actionType: "escalation",
//     ticketId: "TM-240895",
//     oldValue: "in_progress",
//     newValue: "escalated",
//     reason: "SLA threshold breached — wireless coverage.",
//     timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
//   },
//   {
//     logId: "al-005",
//     actorId: "u-admin-2",
//     actorType: "admin",
//     actionType: "reclassification",
//     ticketId: "TM-240898",
//     oldValue: "security/high",
//     newValue: "security/medium",
//     reason: "Noise ratio exceeded threshold; downgrade after tuning.",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
//   },
//   {
//     logId: "al-006",
//     actorId: "u-tech-2",
//     actorType: "technician",
//     actionType: "closure",
//     ticketId: "TM-240901",
//     oldValue: "in_progress",
//     newValue: "resolved",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
//   },
//   {
//     logId: "al-007",
//     actorId: "u-tech-1",
//     actorType: "technician",
//     actionType: "login",
//     timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
//   },
//   {
//     logId: "al-008",
//     actorId: "system",
//     actorType: "system",
//     actionType: "classification",
//     ticketId: "TM-240902",
//     newValue: "security/critical",
//     timestamp: new Date(Date.now() - 1000 * 60 * 148).toISOString(),
//   },
//   {
//     logId: "al-009",
//     actorId: "u-admin-1",
//     actorType: "admin",
//     actionType: "override",
//     ticketId: "TM-240896",
//     oldValue: "priority:52",
//     newValue: "priority:48",
//     reason: "Align with thermal RMA policy.",
//     timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
//   },
//   {
//     logId: "al-010",
//     actorId: "system",
//     actorType: "system",
//     actionType: "classification",
//     ticketId: "TM-240899",
//     newValue: "software/medium",
//     timestamp: new Date(Date.now() - 1000 * 60 * 34).toISOString(),
//   },
//   {
//     logId: "al-011",
//     actorId: "u-tech-3",
//     actorType: "technician",
//     actionType: "reassignment",
//     ticketId: "TM-240897",
//     oldValue: "",
//     newValue: "u-tech-3",
//     timestamp: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
//   },
//   {
//     logId: "al-012",
//     actorId: "u-admin-2",
//     actorType: "admin",
//     actionType: "login",
//     timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
//   },
//   {
//     logId: "al-013",
//     actorId: "system",
//     actorType: "system",
//     actionType: "escalation",
//     ticketId: "TM-240893",
//     oldValue: "in_progress",
//     newValue: "escalated",
//     reason: "Carrier-impacting POS outage.",
//     timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
//   },
//   {
//     logId: "al-014",
//     actorId: "u-tech-1",
//     actorType: "technician",
//     actionType: "closure",
//     ticketId: "TM-240898",
//     oldValue: "in_progress",
//     newValue: "resolved",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
//   },
//   {
//     logId: "al-015",
//     actorId: "system",
//     actorType: "system",
//     actionType: "classification",
//     ticketId: "TM-240904",
//     newValue: "network/critical",
//     timestamp: new Date(Date.now() - 1000 * 60 * 39).toISOString(),
//   },
//   {
//     logId: "al-016",
//     actorId: "u-admin-1",
//     actorType: "admin",
//     actionType: "override",
//     ticketId: "TM-240900",
//     oldValue: "severity:medium",
//     newValue: "severity:high",
//     reason: "Physical security exposure at dock ingress.",
//     timestamp: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
//   },
//   {
//     logId: "al-017",
//     actorId: "u-tech-2",
//     actorType: "technician",
//     actionType: "reclassification",
//     ticketId: "TM-240903",
//     oldValue: "software/medium",
//     newValue: "software/low",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 49).toISOString(),
//   },
//   {
//     logId: "al-018",
//     actorId: "system",
//     actorType: "system",
//     actionType: "classification",
//     ticketId: "TM-240905",
//     newValue: "account/medium",
//     timestamp: new Date(Date.now() - 1000 * 60 * 54).toISOString(),
//   },
//   {
//     logId: "al-019",
//     actorId: "u-admin-1",
//     actorType: "admin",
//     actionType: "login",
//     timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
//   },
//   {
//     logId: "al-020",
//     actorId: "u-admin-2",
//     actorType: "admin",
//     actionType: "override",
//     ticketId: "TM-240902",
//     oldValue: "urgency:medium",
//     newValue: "urgency:high",
//     reason: "Exec readout for privileged access audit.",
//     timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
//   },
// ];
//
// export const MOCK_ESCALATION_RULE: EscalationRule = {
//   ruleId: "er-001",
//   severityThreshold: "high",
//   timeThresholdMinutes: 45,
//   checkIntervalMinutes: 5,
//   notificationTarget: "IT Manager On-Call",
//   isActive: true,
//   version: 12,
//   updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
//   updatedBy: "Priya Sharma",
// };
//
// export const MOCK_ESCALATION_VERSIONS: EscalationRuleVersion[] = [
//   {
//     version: 12,
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
//     changedBy: "Priya Sharma",
//     changes: "Time threshold 45m, notify IT Manager On-Call",
//   },
//   {
//     version: 11,
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
//     changedBy: "Marcus Chen",
//     changes: "Check interval 5m, severity threshold High",
//   },
//   {
//     version: 10,
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
//     changedBy: "Priya Sharma",
//     changes: "Notification target → IT Manager group",
//   },
//   {
//     version: 9,
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
//     changedBy: "Jordan Lee",
//     changes: "Draft sync from staging rule pack",
//   },
//   {
//     version: 8,
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
//     changedBy: "Marcus Chen",
//     changes: "Initial migration from legacy remedy thresholds",
//   },
// ];
//
// export const MOCK_WEEKLY_REPORT: WeeklyReport = {
//   weekOf: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
//   totalTickets: 428,
//   resolvedTickets: 391,
//   avgResolutionTimeHours: 6.4,
//   escalationCount: 27,
//   slaBreachRate: 0.042,
//   topCategories: [
//     { category: "Network", count: 118 },
//     { category: "Software", count: 96 },
//     { category: "Account / IAM", count: 74 },
//     { category: "Hardware", count: 61 },
//     { category: "Security", count: 52 },
//   ],
//   teamBreakdown: [
//     { team: "NOC", resolved: 112, avgTime: 4.2 },
//     { team: "Desktop", resolved: 98, avgTime: 5.8 },
//     { team: "Identity", resolved: 86, avgTime: 3.9 },
//     { team: "Security Ops", resolved: 95, avgTime: 7.1 },
//   ],
// };
//
// /** Volume series for admin charts (last 7 days) */
// export const MOCK_VOLUME_SERIES = [
//   { day: "Mon", tickets: 52 },
//   { day: "Tue", tickets: 61 },
//   { day: "Wed", tickets: 48 },
//   { day: "Thu", tickets: 74 },
//   { day: "Fri", tickets: 69 },
//   { day: "Sat", tickets: 33 },
//   { day: "Sun", tickets: 28 },
// ];
//
// export const MOCK_AI_ACCURACY_SERIES = [
//   { week: "W1", accuracy: 0.91 },
//   { week: "W2", accuracy: 0.92 },
//   { week: "W3", accuracy: 0.9 },
//   { week: "W4", accuracy: 0.93 },
//   { week: "W5", accuracy: 0.94 },
// ];
//
// export function userById(id: string): User | undefined {
//   return MOCK_USERS.find((u) => u.userId === id);
// }
//
// export function categoryIcon(cat: IssueCategory): string {
//   const map: Record<IssueCategory, string> = {
//     network: "Wifi",
//     software: "Monitor",
//     hardware: "Cpu",
//     account: "KeyRound",
//     security: "Shield",
//     other: "HelpCircle",
//   };
//   return map[cat];
// }
